# Author: Pan
# Purpose: IST719 HW2

# Carefully read VT Chapter 4. Complete the Illustrator portions of the 6 chart building exercises in this chapter. Match the examples in the book. Your grade will depend on how close your version matches the book:
#   
#   Bar chart: Fig 4-5
# Stacked bar chart: Fig 4-21
# Scatterplot: Fig 4-25
# Time series: Fig 4-40
# Step chart: Fig 4-42
# LOESS Curve Fig: 4-47

# Load data
unemployment <-
  read.csv(
    "http://datasets.flowingdata.com/unemployment-rate-1948-2010.csv",
    sep=",")
unemployment[1:10,]
# Plain scatter plot
plot(1:length(unemployment$Value), unemployment$Value)

scatter.smooth(x=1:length(unemployment$Value), y=unemployment$Value, ylim=c(0,11), degree=2, col="#CCCCCC", span=0.5)

# Save as PDF from Illustrator. Combine submission into one file and turn in the pdf and your r-script. Since the grade will be based on how closely elements of the plot match how they look in the book. Pay attention to things like:
#   
#   The size and position of text
# The proportions of the plot
# The colors of the background, lines and text
# File name: ex4_lastname.pdf
# Tips
# 
# Try to match the images in the book as exactly as you can.
# Double check spacing, alignments, and labels. 
# Begin by cleaning up the layers that are automatically generated by R when it creates the PDF.
# Discard anything that you do not need.
# If you are having trouble selecting an object, try to right click and choose “Releasing Clipping Mask.” This should release the object and allow you to edit it. You can also try to "Ungroup" elements.